version: '3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword

  web:
    build: .
    command: gunicorn interview_app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - celery_worker
      - celery_beat

  redis:
    image: redis:6.0

  celery_worker:
    build: .
    command: celery -A interview_app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

  celery_beat:
    build: .
    command: celery -A interview_app beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
