name: Run tests

on:
  push:
  pull_request:

jobs:
  run-tests:
  strategy:
    fail-fast: false
    matrix:
      os: [ubuntu-latest, macos-latest, windows-latest]
      python_version:
        - "3.12"

  name: Test
  runs-on: ${{ matrix.os }}

  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Python setup
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: python3 -m pip -r requirements.txt

    - name: Run tests
      run: python3 -m manage.py test